import './globals.css'
import Head from "next/head";
import Navbar from './Navbar';
import Footer from './Footer';
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="flex flex-col min-h-screen h-full">
        <Navbar />
        <main className="flex gap-5 h-full grow">
          <div className="flex flex-col gap-5 w-40 p-5 bg-red-500">
            <Link
              className="font-bold text-black text-xl bg-gray-200 p-3 rounded"
              href="/"
            >
              Home
            </Link>
            <Link
              className="font-bold text-black text-xl bg-gray-200 p-3 rounded"
              href="/blog"
            >
              Blog
            </Link>
            <Link
              className="font-bold text-black text-xl bg-gray-200 p-3 rounded"
              href="/about"
            >
              About
            </Link>
          </div>
          <div className="grow bg-red-500">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
